name: flutter_guid
description: Emulates C# Guid. Generate new UUIDs, add variables of type Guid to classes.
version: 0.3.1
homepage: https://github.com/rocket-libs/flutter_guid

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
